### Assignment Questions
### Section A: Data Structures & Control Structures
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.


In [1]:
list=[100,200,300,400,500] #created a list of 5 integers

list.append(600) #Adds one element at the end of the list
list.extend([700,800]) #Adds multiple elements at the end of the list
list.insert(3,350) # Inserts an element at specified position
list.remove(200) # Removes the first occurrence of the specific element
popped_element=list.pop() #removes and return the last element 
print("Popped element: ",popped_element)
index_pos=list.index(400) #returns the index of the first occurrence of the specific element
print("Index Of ",400,"is",index_pos)
count_ele=list.count(500) #return the no.of times the specific element is appeared
print("count of ",500,"is",count_ele)
list.sort() #sorts the list
print("sorted list:",list)
list.reverse() #reverses the list
print("Reversed list: ",list)
list.clear() #clears all the elements in the list
print("after clearing list:",list)

Popped element:  800
Index Of  400 is 3
count of  500 is 1
sorted list: [100, 300, 350, 400, 500, 600, 700]
Reversed list:  [700, 600, 500, 400, 350, 300, 100]
after clearing list: []


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [4]:
students=("Vishal","Baji","Nikhil")
print("Original tuple: ",students)
try:
    students[1]="Baji"
except TypeError:
    print("Error:Tuples are immutable")

#Here,we cannot change the values in the tuple.Because tuples are immutable.So,if we try to modify the tuple it raises TypeError-->Tuples cannot be changed after creation

Original tuple:  ('Vishal', 'Baji', 'Nikhil')
Error:Tuples are immutable


##### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [6]:
set={10,20,30,30,40,40,50}
print("Set: ",set)
# In sets the duplicate values are removed automatically.

Set:  {50, 20, 40, 10, 30}


4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [9]:
dictionary={
    "name":"Vishal",
    "age":24,
    "city":"Delhi"
}
print("Original Dictionary:",dictionary)
#update age
dictionary["age"]=28

#Add a new key
dictionary["email"]="vishal@gmail.com"

print("final Dictionary: ",dictionary)

Original Dictionary: {'name': 'Vishal', 'age': 24, 'city': 'Delhi'}
final Dictionary:  {'name': 'Vishal', 'age': 28, 'city': 'Delhi', 'email': 'vishal@gmail.com'}


5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [10]:
age=int(input("Enter the age: "))
if age>=18:
    print("Eligible to Vote.")
else:
    print("Not eligible to vote.")

Enter the age:  17


Not eligible to vote.


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [11]:
marks=int(input("Enter the marks: "))
if marks>=90:
    print("Grade : A")
elif marks>=75 and marks<=89:
    print("Grade : B")
elif marks>=50 and marks<=74:
    print("Grade : C")
else:
    print("Grade : Fail")

Enter the marks:  90


Grade : A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [13]:
 n=int(input("Enter a Number: "))
if n>0:
    print("Positive Number.")
    if n%2==0:
        print("It is also an even number")
elif n<0:
    print("Negative Number.")
else:
    print("Zero.")

Enter a Number:  5


Positive Number.


## Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [14]:
import numpy as np
#scalar using np.array()
scalar=np.array(5)
print("Scalar:",scalar)
# A 1D array with values 1 to 5
arr1=np.array([1,2,3,4,5])
print("1D-Array:",arr1)
# A 2D array (2x3) with values from 10 to 60 in steps of 10
arr2=np.array([[10,20,30],
               [40,50,60]])
print("2*3 Array:",arr2)

Scalar: 5
1D-Array: [1 2 3 4 5]
2*3 Array: [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [15]:
import numpy as np
random_array=np.random.randint(0,101,size=(4,4))
print("4*4 random integer array:\n",random_array)

4*4 random integer array:
 [[11 61  8 27]
 [89 65 97 37]
 [30  6  3 23]
 [64 94 69 58]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [18]:
import pandas as pd
array=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Numpy Array:",array)
Pdf=pd.DataFrame(array,columns=['A','B','C'])
print("DataFrame:\n",Pdf)

Numpy Array: [[10 20 30]
 [40 50 60]
 [70 80 90]]
DataFrame:
     A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


### Section C: Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [21]:
import pandas as pd
import numpy as np

# ---- Creating the DataFrame ----
data = {
    "Name": ["John", "Mary", "Alex", "Sara", "Tom",
             "John", "Nina", "Bob", "Alex", "Kim"],
    
    "Age": [25, 30, 22, 28, 35,
            25, 27, 31, 22, 29],
    
    "City": ["Delhi", "Mumbai", "Delhi", "Mumbai", "Chennai",
             "Delhi", "Kolkata", "Chennai", "Delhi", "Mumbai"],
    
    "Salary": [50000, 60000, np.nan, 55000, 70000,
               50000, 62000, np.nan, 54000, 58000]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n")
print(df)

# ---- Using info() ----
print("\n DataFrame Info:\n")
print(df.info())

# ---- Using describe() ----
print("\n DataFrame Description:\n")
print(df.describe())

# ---- Selecting Name and City columns ----
print("\n Selecting Name and City columns :\n")
print(df[["Name", "City"]])

# ---- Dropping the City column ----
aft_drop_city = df.drop("City", axis=1)
print("\n DataFrame after dropping City column:\n")
print(aft_drop_city)

# ---- Filling missing salary values with mean ----
mean_salary = df["Salary"].mean()
print("Mean Salary: ",mean_salary)
df["Salary"].fillna(mean_salary, inplace=True)

print("\n DataFrame after filling missing Salary values:\n")
print(df)

# ---- Removing duplicate rows ----
aft_rem_duplicates = df.drop_duplicates()

print("\n DataFrame after removing duplicates :\n")
print(aft_rem_duplicates)

Original DataFrame:

   Name  Age     City   Salary
0  John   25    Delhi  50000.0
1  Mary   30   Mumbai  60000.0
2  Alex   22    Delhi      NaN
3  Sara   28   Mumbai  55000.0
4   Tom   35  Chennai  70000.0
5  John   25    Delhi  50000.0
6  Nina   27  Kolkata  62000.0
7   Bob   31  Chennai      NaN
8  Alex   22    Delhi  54000.0
9   Kim   29   Mumbai  58000.0

 DataFrame Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

 DataFrame Description:

             Age        Salary
count  10.000000      8.000000
mean   27.400000  57375.000000
std     4.087923   6696.214282
min    22.000000  50000.000000
25%    25.000000  53000.000000
50%    27.50

C:\Users\visha\AppData\Local\Temp\ipykernel_14408\1383188489.py:44: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(mean_salary, inplace=True)
